title: (( ( S i l e n t e S o n o r o ) ))
description: Silente Sonoro genera artesanías copyleft que promueven la comunicación acústica utilizando técnicas de narrativa sonora con medios analógicos y digitales. Hecho con software libre.
show_downloads: false
theme: jekyll-theme-midnight
