title: (( ( S i l e n t e S o n o r o ) ))
description: Artesanías copyleft sobre comunicación acústica y narrativa sonora con medios analógicos y digitales. Hecho con software libre.
show_downloads: false
theme: jekyll-theme-midnight
site.url: https://silente.dyne.org
